# Generated by Django 6.0.5 on 2026-05-20 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CHANGES_REQUESTED', 'Changes Requested'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('FINALIZED', 'Finalized'), ('REJECTED', 'Rejected')], max_length=30)),
                ('new_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CHANGES_REQUESTED', 'Changes Requested'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('FINALIZED', 'Finalized'), ('REJECTED', 'Rejected')], max_length=30)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_status_changes', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='claims.claim')),
            ],
            options={
                'db_table': 'claim_status_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
