# Generated by Django 6.0.5 on 2026-05-20 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceReuseFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_notes', models.TextField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuse_flags', to='claims.evidence')),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_reuse_cases', to=settings.AUTH_USER_MODEL)),
                ('primary_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_reuse_flags', to='claims.claim')),
                ('secondary_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_reuse_flags', to='claims.claim')),
            ],
            options={
                'db_table': 'evidence_reuse_flags',
                'ordering': ['-flagged_at'],
            },
        ),
    ]
