# Generated by Django 6.0.5 on 2026-05-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_evidencereuseflag'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['claim'], name='audit_logs_claim_i_3680fe_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor'], name='audit_logs_actor_i_0badd2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='audit_logs_action_31f574_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status'], name='claims_status_cb731f_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['employee'], name='claims_employe_939c73_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['created_at'], name='claims_created_ba390a_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status', 'created_at'], name='claims_status_7557c7_idx'),
        ),
        migrations.AddIndex(
            model_name='claimstatushistory',
            index=models.Index(fields=['claim'], name='claim_statu_claim_i_f0a59d_idx'),
        ),
        migrations.AddIndex(
            model_name='claimstatushistory',
            index=models.Index(fields=['changed_at'], name='claim_statu_changed_2447ea_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['claim'], name='evidence_claim_i_7e0229_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['content_hash'], name='evidence_content_b31b40_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['uploaded_at'], name='evidence_uploade_69e4a0_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencereuseflag',
            index=models.Index(fields=['evidence'], name='evidence_re_evidenc_f7a97c_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencereuseflag',
            index=models.Index(fields=['primary_claim'], name='evidence_re_primary_98aca3_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencereuseflag',
            index=models.Index(fields=['secondary_claim'], name='evidence_re_seconda_f79140_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencereuseflag',
            index=models.Index(fields=['flagged_at'], name='evidence_re_flagged_b8fd8a_idx'),
        ),
    ]
